version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - apierrors
  - containedctx
  - contextcheck
  - cyclop
  - dataurl
  - depguard
  - Describedby
  - Detailf
  - dupl
  - durationcheck
  - elevenlabs
  - errcheck
  - errchkjson
  - errname
  - execinquery
  - exhaustive
  - exhaustruct
  - exportloopref
  - Facemotion
  - flac
  - forcetypeassert
  - funlen
  - goarch
  - gochecknoglobals
  - gochecknoinits
  - gocognit
  - goconst
  - gocritic
  - gocyclo
  - godox
  - gofmt
  - gofumpt
  - goheader
  - goimports
  - gomnd
  - goprintffuncname
  - gosec
  - gosimple
  - govet
  - hreflang
  - ineffassign
  - ireturn
  - jsonpatch
  - koemotion
  - labstack
  - lll
  - maintidx
  - misspell
  - moeru
  - musttag
  - nakedret
  - nestif
  - nilnil
  - nlreturn
  - nolint
  - nolintlint
  - nosprintfhostport
  - paralleltest
  - perfsprint
  - prealloc
  - predeclared
  - reassign
  - revive
  - Rinna
  - samber
  - staticcheck
  - strconv
  - tagalign
  - tenv
  - testableexamples
  - testpackage
  - Traceparent
  - typecheck
  - unconvert
  - unparam
  - unspeech
  - unused
  - varnamelen
  - Vercel
  - whitespace
  - wrapcheck
  - wsl
ignoreWords: []
import: []
